name: Selenium Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable firefox

      - name: Run Selenium tests on ${{ matrix.browser }}
        run: mvn test -Dbrowser=${{ matrix.browser }}